name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: kiancross/checkstyle-annotations-action@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDist
    - name: Update continuous build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
        prerelease: true
        tag: Continuous
        file: build/distributions/OmegaT_*_Beta_Without_JRE.zip
